// frontend/05-multiple-apps/vue-project/src/components/TodoList/TodoList.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import axios from "axios";
import { v4 as uuidv4 } from "uuid";
import { TodoInput } from "../TodoInput";
import { TodoListItem } from "../TodoListItem";

type Task = {
  id: string;
  text: string;
  isCompleted: boolean;
};

const tasks = ref<Task[]>([]);
const totalTasks = computed(() => tasks.value.length);
const hasValidTasks = computed(() => tasks.value.length > 0);

function handleSubmit(task: string) {
  const newTask = {
    id: uuidv4(),
    text: task,
    isCompleted: false,
  };

  tasks.value = [...tasks.value, newTask];
}

function handleRemoveTask(taskId: string) {
  const updatedTasks = tasks.value.filter((task) => task.id !== taskId);

  tasks.value = updatedTasks;
}

onMounted(() => {
  async function fetchTodos() {
    try {
      const { data } = await axios.get("http://localhost:3000/todos");
      tasks.value = [...tasks.value, ...data];

      /**
       * WARNING: catch was ignored in the test on purpose,
       * don't do this in real applications
       */
      /* c8 ignore next 3 */
    } catch (error) {
      tasks.value = [];
    }
  }

  fetchTodos();
});
</script>

<template>
  <div>
    <h1>Vue - TODO List</h1>

    <p>
      Total items: <span data-testid="total-tasks">{{ totalTasks }}</span>
    </p>

    <TodoInput :onSubmit="handleSubmit" />

    <ul v-if="hasValidTasks">
      <TodoListItem
        v-for="task in tasks"
        :key="task.id"
        :task="task"
        :onRemoveTask="handleRemoveTask"
      />
    </ul>
  </div>
</template>

// frontend/02-create-components/react-project/src/components/TodoList/TodoList.tsx
import axios from "axios";
import { useEffect, useState } from "react";
import { v4 as uuidv4 } from "uuid";
import { TaskProps, TodoListItem } from "../TodoListItem";
import { TodoInput } from "../TodoInput";

function TodoList() {
  const [tasks, setTasks] = useState<TaskProps[]>([]);

  const totalTasks = tasks.length;
  const hasValidTasks = tasks.length > 0;

  function handleSubmit(task: string) {
    const newTask = {
      id: uuidv4(),
      text: task,
      isCompleted: false,
    };

    setTasks((prevState) => [...prevState, newTask]);
  }

  function handleToggleDone(taskId: string) {
    const updatedTasks = tasks.map((task) => {
      if (task.id === taskId) {
        return {
          ...task,
          isCompleted: !task.isCompleted,
        };
      }

      return task;
    });

    setTasks(updatedTasks);
  }

  function handleRemoveTask(taskId: string) {
    const updatedTasks = tasks.filter((task) => task.id !== taskId);

    setTasks(updatedTasks);
  }

  useEffect(() => {
    async function fetchTodos() {
      try {
        const res = await axios.get("http://localhost:3000/todos");
        const tasks = res.data;

        setTasks(tasks);

        /**
         * WARNING: catch was ignored in the test on purpose,
         * don't do this in real applications
         */
        /* c8 ignore next 3 */
      } catch (error) {
        setTasks([]);
      }
    }

    fetchTodos();
  }, []);

  return (
    <div>
      <h1>React - TODO List</h1>

      <p>
        Total items: <span data-testid="total-tasks">{totalTasks}</span>
      </p>

      <TodoInput onSubmit={handleSubmit} />

      {hasValidTasks && (
        <ul>
          {tasks.map((task) => (
            <TodoListItem
              key={task.id}
              task={task}
              onToggleDone={handleToggleDone}
              onRemoveTask={handleRemoveTask}
            />
          ))}
        </ul>
      )}
    </div>
  );
}

export default TodoList;
