// frontend/05-multiple-apps/vue-project/src/components/TodoInput/TodoInput.vue
<script setup lang="ts">
import { ref } from "vue";

type Task = {
  id: number;
  text: string;
  isCompleted: boolean;
};

const { onSubmit } = defineProps<{
  onSubmit: (task: Task) => void;
}>();

const task = ref<string>("");

function handleSubmit() {
  const taskValue = task.value?.trim();

  if (!taskValue.length) {
    return;
  }

  const newTask = {
    id: Date.now(),
    text: taskValue,
    isCompleted: false,
  };

  onSubmit(newTask);
  task.value = "";
}
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <input
      v-model="task"
      type="text"
      placeholder="Type your task and press Enter"
    />
  </form>
</template>

// frontend/02-create-components/react-project/src/components/TodoInput/TodoInput.tsx
import { useState } from "react";
import { TaskProps } from "../TodoListItem";

type Props = {
  onSubmit: (task: TaskProps) => void;
};

function TodoInput(props: Props) {
  const { onSubmit } = props;

  const [task, setTask] = useState<string>("");

  function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
    const task = event.target.value.trim();

    setTask(task);
  }

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!task.length) {
      return;
    }

    const newTask = {
      id: Date.now(),
      text: task,
      isCompleted: false,
    };

    onSubmit(newTask);
    setTask("");
  }

  return (
    <form onSubmit={handleSubmit}>
      <input
        type="text"
        placeholder="Type your task and press Enter"
        value={task}
        onChange={handleChange}
      />
    </form>
  );
}

export default TodoInput;
